version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: casino
    volumes:
      - mongo-data:/data/db
    networks:
      - casino-network

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - casino-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/casino
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - RATE_LIMIT_WINDOW=60
      - RATE_LIMIT_SPINS=10
    depends_on:
      - mongo
      - redis
    networks:
      - casino-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - casino-network

volumes:
  mongo-data:
  redis-data:

networks:
  casino-network:
    driver: bridge
