version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: casino
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/casino
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=myjwtsecret
      - REFRESH_SECRET=myrefreshsecret
      - RATE_LIMIT_WINDOW=60
      - RATE_LIMIT_SPINS=10
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development  
    depends_on:
      - backend

volumes:
  mongo-data:
  redis-data:
